services:
    db:
        image: postgis/postgis:13-3.1
        environment:
            POSTGRES_USER: nodewatcher
            POSTGRES_PASSWORD: nodewatcher
            POSTGRES_DB: nodewatcher
        volumes:
            - nodewatcher-db:/var/lib/postgresql/data
    influxdb:
        image: influxdb:1.8
        environment:
            INFLUXDB_DB: nodewatcher
        volumes:
            - nodewatcher-influxdb:/var/lib/influxdb
    redis:
        image: redis:7-alpine
    # OpenWrt 24.10.5 builder (ath79 target)
    builderath79:
        build:
            context: ./docker/builder-openwrt-2410
            args:
                OPENWRT_VERSION: "24.10.0"
                TARGET: "ath79"
                SUBTARGET: "generic"
        environment:
            BUILDER_PUBLIC_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmHXPrHepYvXms/nv5mNPp+rDE+IsVnOMvavZB9QP36SgkFTJChPU3HQcFUx/UysWdjHECWovqWmaPN4l/ydl4Ag+tQqhFCkMJSTQYSsmFJRzJEeEVRPyxP7v1c6E6xEPbvufa768eNkrEnAn4eFVcqWzrOWFyof+FcPrH573c0Yza7D7sNEueqWWX/uLxd72Mi9pIK6KsVVY96t7QHUNS6LCC4YILYnNUIKZ+KdAQux/SNFOSq1VYG1i6HN6wztS2tYHrmRIQRq0VpQq/zuvCm0c0g/CKeWXeMLQVcjdktSU+3LJPUTVSjQDf8gdOtiecbKLI1T2+KR7G5rf2wAbD builder@nodewatcher
    generator:
        build: .
        command: "scripts/docker-cleanup; scripts/docker-wait-pgsql; celery -A nodewatcher worker -l info -Q generator"
        entrypoint: scripts/docker-run
        environment:
            # Allow celery to run under the root user in order for it to have access
            C_FORCE_ROOT: "true"
        volumes:
            - .:/code
        links:
            - db
            - influxdb
            - redis
            - builderath79
    monitorq:
        build: .
        command: "scripts/docker-cleanup; scripts/docker-wait-pgsql; celery -A nodewatcher worker -l info -Q monitor -B"
        entrypoint: scripts/docker-run
        environment:
            # Allow celery to run under the root user in order for it to have access
            C_FORCE_ROOT: "true"
        volumes:
            - .:/code
        links:
            - db
            - influxdb
            - redis
    web:
        build: .
        command: "scripts/docker-cleanup; scripts/docker-wait-pgsql; python manage.py runserver 0.0.0.0:8000"
        entrypoint: scripts/docker-run
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        links:
            - db
            - influxdb
            - redis
            - builderath79

volumes:
    nodewatcher-db:
    nodewatcher-influxdb:
