server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /home/builder;

    location /packages/ {
        alias /home/builder/imagebuilder/packages/;
        autoindex on;
    }

    location /metadata {
        alias /home/builder/packages/metadata.json;
        default_type application/json;
    }

    location /metadata/ {
        alias /home/builder/packages/;
        autoindex on;
    }

    location / {
        return 404;
    }
}
