# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfig',
            name='annotations',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='roles',
            field=nodewatcher.core.registry.fields.RegistryMultipleChoiceField(base_field=models.CharField(choices=[('system', 'System node'), ('border-router', 'Border router'), ('vpn-server', 'VPN server'), ('redundancy-required', 'Node with redundant links requirement')], max_length=50), blank=True, default=list, enum_id='core.roles#roles', null=True, regpoint='node.config', size=None),
        ),
    ]
