# Generated by Django 4.2.27 on 2025-12-19 11:22

from django.db import migrations, models
import django.db.models.deletion
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatediprouteridconfig',
            name='allocation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations_%(app_label)s_%(class)s', to='core.ippool'),
        ),
        migrations.AlterField(
            model_name='allocatediprouteridconfig',
            name='pool',
            field=nodewatcher.core.registry.fields.ModelRegistryChoiceField(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.PROTECT, to='core.ippool'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='annotations',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='root',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='config_%(app_label)s_%(class)s', to='core.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='registry_metadata',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='routeridconfig',
            name='annotations',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='routeridconfig',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='routeridconfig',
            name='root',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='config_%(app_label)s_%(class)s', to='core.node'),
        ),
    ]
