# Generated by Django 4.2.27 on 2025-12-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_allocatediprouteridconfig_allocation_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiAirtimeMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('interface', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('busy_time', models.BigIntegerField(help_text='Channel busy time in microseconds', null=True)),
                ('receive_time', models.BigIntegerField(help_text='Receive time in microseconds', null=True)),
                ('transmit_time', models.BigIntegerField(help_text='Transmit time in microseconds', null=True)),
                ('active_time', models.BigIntegerField(help_text='Active time in microseconds', null=True)),
                ('busy_percent', models.FloatField(help_text='Channel busy percentage', null=True)),
                ('rx_percent', models.FloatField(help_text='RX airtime percentage', null=True)),
                ('tx_percent', models.FloatField(help_text='TX airtime percentage', null=True)),
                ('channel', models.IntegerField(help_text='Current channel', null=True)),
                ('channel_width', models.IntegerField(help_text='Channel width in MHz', null=True)),
                ('noise_floor', models.IntegerField(help_text='Noise floor in dBm', null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeshQualityMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('peer_id', models.CharField(help_text='Peer node identifier', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('link_quality', models.FloatField(help_text='Link quality (0-1)', null=True)),
                ('neighbor_link_quality', models.FloatField(help_text="Neighbor's link quality (0-1)", null=True)),
                ('expected_throughput', models.BigIntegerField(help_text='Expected throughput in Kbps', null=True)),
                ('signal_strength', models.IntegerField(help_text='Signal strength in dBm', null=True)),
                ('signal_noise', models.IntegerField(help_text='Signal noise in dBm', null=True)),
                ('snr', models.FloatField(help_text='Signal to noise ratio in dB', null=True)),
                ('tx_packets', models.BigIntegerField(help_text='Transmitted packets', null=True)),
                ('rx_packets', models.BigIntegerField(help_text='Received packets', null=True)),
                ('tx_bytes', models.BigIntegerField(help_text='Transmitted bytes', null=True)),
                ('rx_bytes', models.BigIntegerField(help_text='Received bytes', null=True)),
                ('tx_retries', models.BigIntegerField(help_text='TX retries', null=True)),
                ('tx_failed', models.BigIntegerField(help_text='TX failures', null=True)),
                ('mcs_rate', models.IntegerField(help_text='MCS rate index', null=True)),
                ('bitrate', models.FloatField(help_text='Current bitrate in Mbps', null=True)),
                ('protocol', models.CharField(help_text='Mesh protocol (batman, olsr, babel)', max_length=50, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelSurveyMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('interface', models.CharField(max_length=50)),
                ('channel', models.IntegerField(help_text='Channel number')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('frequency', models.IntegerField(help_text='Frequency in MHz', null=True)),
                ('noise_floor', models.IntegerField(help_text='Noise floor in dBm', null=True)),
                ('active_time', models.BigIntegerField(help_text='Active time in ms', null=True)),
                ('busy_time', models.BigIntegerField(help_text='Busy time in ms', null=True)),
                ('receive_time', models.BigIntegerField(help_text='Receive time in ms', null=True)),
                ('transmit_time', models.BigIntegerField(help_text='Transmit time in ms', null=True)),
                ('busy_percent', models.FloatField(help_text='Channel utilization percentage', null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
