# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_network_profile', '0005_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprofileconfig',
            name='annotations',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='networkprofileconfig',
            name='profiles',
            field=nodewatcher.core.registry.fields.RegistryMultipleChoiceField(base_field=models.CharField(choices=[('routing-over-wan', 'Routing over WAN port'), ('backbone-with-uplink', 'Backbone node with uplink'), ('nat-clients', 'Clients behind NAT'), ('no-lan-bridge', "Don't bridge LAN port with clients"), ('mobile-uplink', 'Use a mobile interface for uplink'), ('wifi-uplink', 'Use a wireless interface for uplink'), ('no-wifi-ap', 'Disable wireless AP'), ('no-wifi-mesh', 'Disable wireless mesh'), ('hostname-essid', 'Use hostname as ESSID')], max_length=50), blank=True, default=list, enum_id='network.profile#profiles', help_text='Selected network profiles affect how the node is configured when automatic defaults are enabled. In case defaults are disabled, selecting network profiles will have no effect.', null=True, regpoint='node.config', size=None),
        ),
    ]
