# Generated by Django 4.2.27 on 2025-12-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_allocatediprouteridconfig_allocation_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('voltage', models.FloatField(help_text='Input voltage in V', null=True)),
                ('current', models.FloatField(help_text='Current draw in A', null=True)),
                ('power_watts', models.FloatField(help_text='Power consumption in W', null=True)),
                ('power_source', models.CharField(help_text='Power source (ac, poe, battery)', max_length=50, null=True)),
                ('poe_standard', models.CharField(help_text='PoE standard if applicable', max_length=50, null=True)),
                ('battery_percent', models.FloatField(help_text='Battery percentage if on battery', null=True)),
                ('uptime_seconds', models.BigIntegerField(help_text='Uptime in seconds', null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryDetailedMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total', models.BigIntegerField(help_text='Total RAM in bytes', null=True)),
                ('free', models.BigIntegerField(help_text='Free RAM in bytes', null=True)),
                ('available', models.BigIntegerField(help_text='Available RAM in bytes', null=True)),
                ('buffers', models.BigIntegerField(help_text='Buffer memory in bytes', null=True)),
                ('cached', models.BigIntegerField(help_text='Cached memory in bytes', null=True)),
                ('swap_total', models.BigIntegerField(help_text='Total swap in bytes', null=True)),
                ('swap_free', models.BigIntegerField(help_text='Free swap in bytes', null=True)),
                ('usage_percent', models.FloatField(help_text='RAM usage percentage', null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashHealthMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_bytes', models.BigIntegerField(help_text='Total flash size in bytes', null=True)),
                ('used_bytes', models.BigIntegerField(help_text='Used space in bytes', null=True)),
                ('free_bytes', models.BigIntegerField(help_text='Free space in bytes', null=True)),
                ('usage_percent', models.FloatField(help_text='Usage percentage', null=True)),
                ('write_cycles', models.BigIntegerField(help_text='Estimated write cycles', null=True)),
                ('bad_blocks', models.IntegerField(help_text='Number of bad blocks', null=True)),
                ('health_percent', models.FloatField(help_text='Overall health percentage', null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CpuTemperatureMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.JSONField(default=dict, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(help_text='CPU temperature in Celsius', null=True)),
                ('temperature_max', models.FloatField(help_text='Maximum safe temperature', null=True)),
                ('thermal_throttling', models.BooleanField(default=False, help_text='CPU is thermal throttling')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_%(app_label)s_%(class)s', to='core.node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
